name: "Build docker image"

on:
  push:
    # 一旦Action無効化
    # branches:
    #   - main
    #   - master
    # paths:
    #   - ".devcontainer/**/*"
    branches-ignore:
      - "**"

  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      devcontainer: ${{ steps.filter.outputs.devcontainer }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            devcontainer:
              - ".devcontainer/**/*"

  build-devcontainer:
    needs:
      - detect-changes
    if: needs.detect-changes.outputs.devcontainer == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: aazw
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image and push
        uses: docker/build-push-action@v6
        with:
          context: ./.devcontainer/
          file: ./.devcontainer/Dockerfile
          push: true
          tags: |
            ghcr.io/aazw/vscode-base:${{ github.run_number }}
